#!/bin/bash

################## Parent Directories
HOME_DIR="/home/alireza/Desktop/offline_autoloc/Automated_Playback"
SEISCOMP_DIR="/home/alireza/seiscomp3"


################### DO NOT CHANGE ANYTHING BELOW
PROCESS_DIR="$HOME_DIR/PROCESS"
BACKUP="$HOME_DIR/BackUp"
OUTPUT="$HOME_DIR/Output"
INPUT="$HOME_DIR/Input"
SCRIPT=`echo $0 | cut -f 2 -d "/"`


USAGE ()
{
	cat <<- EOF
	Usage []:
	$0 -d <DATABASE>
	-d : Specifies the database. e.g mysql://sysop:sysop@HOST/seiscomp3
	OPTIONS:
	-h : Print help message
	EOF
}


PRE_PROCESS ()
{
	cp -f "$mseed" "$BACKUP" 2> /dev/null
	[[ `ls $PROCESS_DIR/* 2> /dev/null` ]] && rm -f "$PROCESS_DIR"/*
	
	jackseis "$mseed" --output-dir="$PROCESS_DIR" --output-format="mseed" --output=trace.%n.%s.%c
	cd "$PROCESS_DIR"
	for data in `ls trace*`; do
		sta=`echo $data | cut -f 3 -d "."`
		[ ! `ls $SEISCOMP_DIR/etc/key/*$sta 2> /dev/null` ] && continue
		net=`ls $SEISCOMP_DIR/etc/key/*$sta | cut -f 2 -d "_"`
		if [ \( "$net" = "IR" \) -o \( "$net" = "BI" \) ]; then
			enz=`echo $data | cut -f 4 -d "."`; enz="${enz:2:1}"
			channel=`grep "global" $SEISCOMP_DIR/etc/key/*$sta | awk -F ":" '{print substr($2,1,2)}'`
			msmod --net "$net" --chan "$channel$enz" -i $data
		fi
	done		
	[ -f "$HOME_DIR"/Prepared_Data.mseed ] && rm -f "$HOME_DIR"/Prepared_Data.mseed 
	cat trace* > "$HOME_DIR"/Prepared_Data.mseed 
	cd "$INPUT"
}



PROCESS ()
{	
	echo "Starting scautoloc ..."
	seiscomp exec scautoloc -d "$DATABASE" --ep $OUTPUT/$NAME/PICKS.xml --offline --debug > $OUTPUT/$NAME/ORIGINS.xml 2>> $OUTPUT/$NAME/log.dat
	echo "Starting scamp ..."
	seiscomp exec scamp -d "$DATABASE" --ep $OUTPUT/$NAME/ORIGINS.xml --debug > $OUTPUT/$NAME/AMPLITUDES.xml 2>> $OUTPUT/$NAME/log.dat
	echo "Starting scmag ..."
	seiscomp exec scmag -d "$DATABASE" --ep $OUTPUT/$NAME/AMPLITUDES.xml --debug > $OUTPUT/$NAME/MAGS.xml 2>> $OUTPUT/$NAME/log.dat
	echo "Starting scevent ..."
	seiscomp exec scevent -d "$DATABASE" --ep $OUTPUT/$NAME/MAGS.xml --debug > $OUTPUT/$NAME/EVENT.xml 2>> $OUTPUT/$NAME/log.dat
	echo "Starting scdb ..."
	seiscomp exec scdb -d "$DATABASE" -i $OUTPUT/$NAME/EVENT.xml --debug  2>> $OUTPUT/$NAME/log.dat
	
	grep -w "caching event" $OUTPUT/$NAME/log.dat | awk '{print $6}' > $OUTPUT/$NAME/event_ID.log
	
	if [ -s $OUTPUT/$NAME/event_ID.log ]; then
		mkdir $OUTPUT/$NAME/INFO
		cat $OUTPUT/$NAME/event_ID.log | while read EVEID; do
			seiscomp exec scbulletin -E $EVEID -3 -d "$DATABASE" > $OUTPUT/$NAME/INFO/$EVEID.info
		done	
	fi	
}


ARGS ()
{
	[ -z "$HOME_DIR" ] && echo -e "Please set the \"HOME_DIR\" Path in the program's script and try again.\nIt must be the absolute path to the \"$SCRIPT\" script" && exit
	[ -z "$SEISCOMP_DIR" ] && echo "Please set the \"SEISCOMP_DIR\" Path in the program's script and try again." && exit
	
	[[ ! `ls $INPUT` ]] && echo "No input data available ..." && exit
	
	[ -z "$DATABASE" ] && echo -e "No database specified.\nUse $0 -h to see help message..." && exit

	[[ ! `grep -i "msmod" ~/.bashrc` ]] && echo -e "It seems you haven't installed msmod software!\n\
		If so, install it and add its path to ~/.bashrc and try again." && exit
	[[ ! `jackseis` ]] && echo -e "It seems you haven't installed Pyrocko software!\n\
		If so, install it and try again." && exit
}	

while getopts "d:h" options; do
	case $options in
		h)
			USAGE && exit
		;;
		d)
			DATABASE="$OPTARG"		
		;;
		\?)
			USAGE && exit
		;;
	esac
done

#~~~~~~~~~~~~ 
ARGS
echo "#~~~~~~~~~~~~~"
seiscomp start scmaster spread 
echo "#~~~~~~~~~~~~~"

cd "$INPUT"
read -a archives <<< `ls -d -1 */ 2> /dev/null | cut -f 1 -d "/"`
read -a files <<< `ls -1 *mseed 2> /dev/null`

for archive in `echo ${archives[@]}`; do
	NAME="$archive"
	[ ! -f $archive/time.conf ] && echo "No time_config file excists for $archive. skipping ..." && continue
	TIME_RANGE=`grep "~" $archive/time.conf`
	[ "${#TIME_RANGE}" -ne "39" ] && echo -e "The specified time range for $archive has a wrong syntax\nCurrent syntax is YYYY/MM/DD hh:mm:ss~YYYY/MM/DD hh:mm:ss" && continue
	[ ! -d "$OUTPUT/$NAME" ] && mkdir $OUTPUT/$NAME || rm -rf $OUTPUT/$NAME/*
	echo "Starting scautopic ..."
	seiscomp exec scart -dsvE -t "$TIME_RANGE" "$archive" 2> $OUTPUT/$NAME/log.dat | seiscomp exec scautopick -I - \
	-d "$DATABASE" --playback --debug --ep > $OUTPUT/$NAME/PICKS.xml 2> $OUTPUT/$NAME/log.dat
	PROCESS
done	


for mseed in `echo ${files[@]}`; do
	NAME="${mseed%.*}"
	[ ! -d "$OUTPUT/$NAME" ] && mkdir $OUTPUT/$NAME || rm -rf $OUTPUT/$NAME/*
	PRE_PROCESS
	echo "Starting scautopic ..."
	seiscomp exec scautopick -I "$HOME_DIR"/Prepared_Data.mseed -d "$DATABASE" --playback --ep --debug > $OUTPUT/$NAME/PICKS.xml 2> $OUTPUT/$NAME/log.dat
	PROCESS
done
