#!/bin/bash

USAGE ()
{
	cat <<- EOF
	Usage []:
	$0 [-f <MSEED_FILE> | -a <Archive>] -t <TIME_RANGE> -d <DATABASE> -n <NAME>
	-f : Specify the absolute path to the input mseed_file 
	-a : Specify the path to the archive to extract data from (requires -t option)
	-t : Specify the time range for data extraction (only with -a option)
		 Syntax is <'YYYY/MM/DD hh:mm:ss~YYYY/MM/DD hh:mm:ss'>
	-d : Specify the database. e.g mysql://sysop:sysop@HOST/seiscomp3
	-n : Specify the event Name for processing	
	OPTIONS:
	-h : Print help message
	EOF
}


PROCESS ()
{	
	echo "Starting scautopic ..."
	if [ -f "$MSEEDFILE" ]; then
		seiscomp exec scautopick -I "$MSEEDFILE" -d "$DATABASE" --playback --ep --debug > $NAME/PICKS.xml 2> $NAME/log.dat
	else
		seiscomp exec scart -dsvE -t "$TIME_RANGE" "$ARCHIVE" 2> $NAME/log.dat | seiscomp exec scautopick -I - \
		-d "$DATABASE" --playback --debug --ep > $NAME/PICKS.xml 2> $NAME/log.dat
	fi
	echo "Starting scautoloc ..."
	seiscomp exec scautoloc -d "$DATABASE" --ep $NAME/PICKS.xml --offline --debug > $NAME/ORIGINS.xml 2>> $NAME/log.dat
	echo "Starting scamp ..."
	seiscomp exec scamp -d "$DATABASE" --ep $NAME/ORIGINS.xml --debug > $NAME/AMPLITUDES.xml 2>> $NAME/log.dat
	echo "Starting scmag ..."
	seiscomp exec scmag -d "$DATABASE" --ep $NAME/AMPLITUDES.xml --debug > $NAME/MAGS.xml 2>> $NAME/log.dat
	echo "Starting scevent ..."
	seiscomp exec scevent -d "$DATABASE" --ep $NAME/MAGS.xml --debug > $NAME/EVENT.xml 2>> $NAME/log.dat
	echo "Starting scdb ..."
	seiscomp exec scdb -d "$DATABASE" -i $NAME/EVENT.xml --debug  2>> $NAME/log.dat
	
	grep -w "caching event" $NAME/log.dat | awk '{print $6}' > $NAME/event_ID.log
	
	if [ -s $NAME/event_ID.log ]; then
		mkdir $NAME/INFO
		cat $NAME/event_ID.log | while read EVEID; do
			seiscomp exec scbulletin -E $EVEID -3 -d "$DATABASE" > $NAME/INFO/$EVEID.info
		done	
	fi	
}


while getopts "f:d:a:t:n:h" options; do
	case $options in
		h)
			USAGE && exit
		;;
		f)
			MSEEDFILE="$OPTARG"
		;;	
		a)
			ARCHIVE="$OPTARG"	
		;;
		d)
			DATABASE="$OPTARG"
		;;
		t)
			TIME_RANGE="$OPTARG"
		;;	
		n)
			NAME="$OPTARG"			
		;;
		\?)
			USAGE && exit
		;;
	esac
done

# Check arguments availablity ...

[ \( -f "$MSEEDFILE" \) -a \( -d "$ARCHIVE" \) ] && echo -e "You can not use -f and -a options simultaneously.\nUse $0 -h to see help message..." && exit
[ \( ! -f "$MSEEDFILE" \) -a \( ! -d "$ARCHIVE" \) ] && echo -e "You must provide an Archive dir or mseed data.\nUse $0 -h to see help message..." && exit
[ \( -f "$MSEEDFILE" \) -a \( -n "$TIME_RANGE" \) ] && echo -e "-t option only must be used with -a option.\nUse $0 -h to see help message..." && exit

if [ \( -d "$ARCHIVE" \) -a \( -z "$TIME_RANGE" \) ]; then
	echo -e "Please specify a time range for data extraction.\nUse $0 -h to see help message..." && exit
elif [ \( -d "$ARCHIVE" \) -a \( "${#TIME_RANGE}" -ne "39" \) ]; then
	echo "The currect syntax for -t option is <'YYYY/MM/DD hh:mm:ss~YYYY/MM/DD hh:mm:ss'>" && exit
fi
	
[ -z "$DATABASE" ] && echo -e "No database specified.\nUse $0 -h to see help message..." && exit
[ -z "$NAME" ] && read -p "No event ID specified. Please Enter an Event-ID: " NAME
[ ! -d "$NAME" ] && mkdir $NAME || rm -f $NAME/*

echo "#~~~~~~~~~~~~~"
seiscomp start scmaster spread 
echo "#~~~~~~~~~~~~~"

PROCESS

